PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX toi:<http://trebor.org/instance/>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX too:<http://trebor.org/ns#>

SELECT
  ?subject ?predicate ?object
WHERE
{
  bind (%s as ?target)

  ?subject ?predicate ?object.

  FILTER (?subject = ?target || ?object = ?target)
}